### ISSUE TITLE
szkoleniowiec

### ISSUE THREAD

**Issue by MichalKandybowicz** [krozum/pokelife#11]
planujesz wprowadzić ponownie funkcje wbijania szkoleniowca?

**Comment by krozum** [comment]
Postaram się dodać to w najbliższej wersji, natomiast muszę jeszcze przemyśleć czy może wrócić w obecnej wersji, dojdą pewnie jakieś timeouty

**Comment by krozum** [comment]
5.1.1 (2020-01-28)

Przywrócenie wbijania szkoleniowca, dodano timeouty po 1s,gdyby było uciążliwe będą korygowane. 100 pokemonów powinno wbijać około 15m. Przycisk znajduje sie w zakładce Pokemony -> Przechowalnia
