### ISSUE TITLE
Bot nie działa

### ISSUE THREAD

**Issue by Villainous212** [krozum/pokelife#23]
Nie wiem czemu, ale po najnowszej aktualizacji pokelife, bot mi nie działa, mam go włącznone i tempermonky go wykrywa i pokazuje, że niby wszystko jest ok, ale poza tym to nic więcej się nie dzieje tzn. wszystkie opcje są bota niewidoczne i w sumie tak jakby go nie było. Próbowałem przeinstalować kod kilkukrotnie, ale to też nic nie dało :/

**Comment by krozum** [comment]
Po wrzuceniu linku do bota Ethel wprowadził zabezpieczenia pod bota. Wyłączyłem go na razie aby nikt nie złapał bana.

**Comment by Villainous212** [comment]
Aha, to spoko w takim razie. Czekam na ponowne uruchomienie, bo bot jest świetny.

**Comment by krozum** [comment]
Bot działa juz
